namespace Generator.InspectorGen;

public static class InspectorGeneratorData
{
    public static string MakeInspectorFileName(string typeName) => $"{typeName}.InspectorBindings.g.cs";
    public const string InspectorNs = "ConcreteEngine.Editor.Lib.Inspection";

    public const string AttributeFile = "InspectFieldAttributes.g.cs";
    
    public const string AttribInspect = "ConcreteEngine.Core.Engine.Editor.InspectAttribute";

    public const string AttribFieldNs = "ConcreteEngine.Core.Engine.Editor.InputFieldAttribute";
    public const string AttribSliderNs = "ConcreteEngine.Core.Engine.Editor.SliderFieldAttribute";
    public const string AttribDragNs = "ConcreteEngine.Core.Engine.Editor.DragFieldAttribute";
    public const string AttribColorNs = "ConcreteEngine.Core.Engine.Editor.ColorFieldAttribute";
    public const string AttribComboNs = "ConcreteEngine.Core.Engine.Editor.ComboFieldAttribute";

    public const string AttributeSource =
        """
        // <auto-generated/>
        namespace ConcreteEngine.Core.Editor;

        public enum FieldWidgetKind : byte
        {
            Input, Slider, Drag, Combo, Composite,
        }

        [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
        public sealed class InspectValueAttribute : System.Attribute
        {
            public FieldKind Kind { get; }
            public string? Label { get; set; }
            public string? Format { get; set; }
            public float Min { get; set; }
            public float Max { get; set; }
            public float Speed { get; set; }
            public InspectFloatAttribute(FieldWidgetKind kind) => Kind = kind;
        }

        [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
        public sealed class InspectColorAttribute : System.Attribute
        {
            public string? Label { get; set; }
            public bool HasAlpha { get; set; }
            public InspectColorAttribute() {}
        }
        
        [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
        public sealed class InspectMapAttribute : System.Attribute
        {
            public string? Label { get; set; }
            public string? Placeholder { get; set; }
            public int StartAt { get; set; }
            public InspectMapAttribute() {}
        }
        """;
}