namespace Generator.InspectorGen;

file static class Helpers
{
    public static void GenerateHeaders(SourceBuilder sb, string ns)
    {
        sb.AutoGeneratedHeader(nameof(InspectorGenerator));
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ConcreteEngine.Core.Common.Numerics;");
        sb.AppendLine("using ConcreteEngine.Core.Engine.Editor;");
        sb.AppendLine("using ConcreteEngine.Editor.Lib.Inspection;");
        sb.AppendLine("using ConcreteEngine.Editor.Lib.Widgets;").AppendLine();

        sb.AppendLine($"namespace {ns};").AppendLine();

    }


}

public sealed partial class InspectorGenerator
{

    private static string Emit(InspectModel model)
    {
        var sb = new SourceBuilder();
        Helpers.GenerateHeaders(sb,model.InspectorNs);

        sb.AppendLine($"internal static partial class {model.InspectorName}");
        sb.OpenBrace();

        // Members
        foreach (var m in model.Members)
        {
            if (m.Field is null) continue;
            EmitInputField(m, sb);
            sb.AppendLine();
        }

        // Draw
        sb.AppendLine().AppendLine($"public static unsafe void Draw()");
        sb.OpenBrace();
        foreach (var m in model.Members)
        {
            if (m.Field is null) continue;
            sb.AppendLine(m.Name, ".Draw();");
        }

        sb.CloseBrace(); // Draw

        sb.CloseBrace(); // class
        return sb.ToString();
    }

    private static void EmitInputField(TargetMemberInfo member, SourceBuilder sb)
    {
        var fullPath = member.NestedMemberName is null
            ? $"Target.{member.Name}"
            : $"Target.{member.NestedMemberName}.{member.Name}";

        var targetPath = member.NestedMemberName is null
            ? null
            : $"Target.{member.NestedMemberName}";

        switch (member.Field)
        {
            case ColorField colorField:
                sb.NewLine("private static readonly ");
                EmitColorInput(colorField, member, sb, fullPath, targetPath);
                return;
            case InputField input:
                sb.NewLine("private static readonly ");
                EmitInput(input, member, sb, fullPath, targetPath);
                break;
        }
    }

    private static void EmitColorInput(ColorField colorField,TargetMemberInfo member, SourceBuilder sb, string fullPath, string? targetPath)
    {
        
        string castTo = "", castFrom = "", typeName = member.TypeName;
        if (typeName.EndsWith("Vector3") || typeName.EndsWith("Vector4") || typeName.EndsWith("ColorRgba"))
        {
            castTo = $"({member.TypeName})";
            castFrom = "(Color4)";
        }

        sb.Append("ColorInput ", colorField.Name, " = new(").EndLine();
        sb.PushIndent();
        
        sb.AppendLine(Symbols.FormatLiteral(colorField.Label, true), ", ");
        
        // Getter
        sb.AppendLine($"static () => {castFrom}{fullPath}, ");
        
        // Setter
        if (member.ParentInfo is {} p && p.IsStructProperty() && targetPath is not null)
            sb.AppendLine($"static v => {targetPath} = {targetPath} with {{ {member.Name} = {castTo}v }}, ");
        else
            sb.AppendLine($"static v => {fullPath} = {castTo}v, ");

        sb.AppendLine(Symbols.FormatPrimitive(colorField.HasAlpha, false, false));
        sb.PopIndent();
        sb.AppendLine(");");

    }
    
    private static void EmitInput(InputField input,TargetMemberInfo member, SourceBuilder sb, string fullPath, string? targetPath)
    {
        //var comp = (int)char.GetNumericValue(field.ValueType[^1]);
        var inputStyle = $"{nameof(InputStyle)}.{input.InputStyle.ToString()}";
        
        var inputClass = input.IsFloat ? "FloatInput" : "IntInput";
        sb.Append(inputClass, $"<{input.ValueType}> ", input.Name, " = new(");
        sb.EndLine();

        sb.PushIndent();
        sb.AppendLine(Symbols.FormatLiteral(input.Label, true), ", ").AppendLine(inputStyle, ", ");
        
        // Getter
        sb.AppendLine($"static () => Unsafe.BitCast<{member.TypeName}, {input.ValueType}>({fullPath}), ");

        // Setter
        var bitCastV = $"Unsafe.BitCast<{input.ValueType}, {member.TypeName}>(v)";
        if (member.ParentInfo is {} parent && parent.IsStructProperty() && targetPath is not null)
            sb.AppendLine($"static v => {targetPath} = {targetPath} with {{ {member.Name} = {bitCastV} }}, ");
        else
            sb.AppendLine($"static v => {fullPath} = {bitCastV}, ");
        
        //
        sb.NewLine();
        if (input.IsFloat)
        {
            sb.Append(input.Speed).Append(", ").Append(input.Min).Append(", ").Append(input.Max);
            if (input.Format is not null) sb.Append(", ").Append(input.Format);
        }
        else
        {
            sb.Append(input.Speed).Append(", ").Append((int)input.Min).Append(", ").Append((int)input.Max);
        }

        sb.EndLine();

        sb.PopIndent();
        sb.AppendLine(");");

    }
}