namespace Generator.InspectorGen;

internal sealed record InspectorItem
{
    public enum FieldKind : byte
    {
        Input, Slider, Drag, Combo, Composite,
    }

    public required string TypeName { get; set; }
    public required string GlobalTypeName { get; set; }

    public required string MemberName { get; set; }
    public required string MemberTypeName { get; set; }
    public bool MemberIsProperty { get; set; }

    public required string Label { get; set; }
    public string? Format { get; set; }

    public float Min { get; set; }
    public float Max { get; set; }
    public float Speed { get; set; }
    public FieldKind Kind { get; set; }
}

public static class InspectorGeneratorData
{
    public static string MakeInspectorFileName(string typeName) => $"{typeName}.InspectorBindings.g.cs";
    public const string InspectorNs = "ConcreteEngine.Editor.Lib.Inspection";

    public const string AttributeFile = "InspectFieldAttributes.g.cs";
    public const string AttribInspectValueNs = "ConcreteEngine.Core.Editor.InspectValueAttribute";
    public const string AttribInspectColorNs = "ConcreteEngine.Core.Editor.InspectColorAttribute";
    public const string AttribInspectMapNs = "ConcreteEngine.Core.Editor.InspectMapAttribute";

    public const string AttributeSource =
        """
        // <auto-generated/>
        namespace ConcreteEngine.Core.Editor;

        public enum FieldWidgetKind : byte
        {
            Input, Slider, Drag, Combo, Composite,
        }

        [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
        public sealed class InspectValueAttribute : System.Attribute
        {
            public FieldKind Kind { get; }
            public string? Label { get; set; }
            public string? Format { get; set; }
            public float Min { get; set; }
            public float Max { get; set; }
            public float Speed { get; set; }
            public InspectFloatAttribute(FieldWidgetKind kind) => Kind = kind;
        }

        [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
        public sealed class InspectColorAttribute : System.Attribute
        {
            public string? Label { get; set; }
            public bool HasAlpha { get; set; }
            public InspectColorAttribute() {}
        }
        
        [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
        public sealed class InspectMapAttribute : System.Attribute
        {
            public string? Label { get; set; }
            public string? Placeholder { get; set; }
            public int StartAt { get; set; }
            public InspectMapAttribute() {}
        }
        """;
}