using System.Diagnostics;

namespace Generator.InspectorGen;

internal static class InspectorGeneratorEmitter
{
    private readonly record struct AccessPath(string Owner, string Value, bool UsesStructCopy);

    internal readonly record struct EmitSegment(string? Name, EquatableArray<InspectorMember> Members)
    {
        public bool IsDefault => string.IsNullOrEmpty(Name);
    }

    private static void GenerateHeaders(SourceBuilder sb, string ns)
    {
        sb.AutoGeneratedHeader(nameof(InspectorGenerator));
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ConcreteEngine.Core.Common.Numerics;");
        sb.AppendLine("using ConcreteEngine.Core.Engine.Editor;");
        sb.AppendLine("using ConcreteEngine.Editor.Lib.Field;\n");

        sb.AppendLine("namespace ", ns, ";\n");
    }


    public static string Emit(InspectModel model)
    {
        var sb = new SourceBuilder(4096 * 2);
        GenerateHeaders(sb, model.InspectorNs);

        sb.AppendLine("internal sealed partial class ", model.InspectorName);
        sb.OpenBrace();

        // Groups
        foreach (var group in model.Groups.AsSpan())
        {
            if (group.Members.Length == 0) continue;

            sb.AppendLine("// ", group.Name);
            var segments = BuildSegments(group);
            foreach (var segment in segments.AsSpan())
            {
                if(!segment.IsDefault) sb.AppendLine().AppendLine("// ", segment.Name!);

                foreach (var member in segment.Members.AsSpan())
                {
                    EmitInputField(sb, member, group);
                }
            }

            var isRoot = group.IsRoot;
            foreach (var segment in segments.AsSpan())
            {
                if(segment.Members.Length == 0) continue;
                
                sb.AppendLine().BeginLine("public void Draw");
                if (isRoot) sb.Append(segment.IsDefault ? "Root" : segment.Name!); // DrawRoot, DrawSegment
                else if (segment.IsDefault) sb.Append(group.Name); // DrawGroup
                else sb.Append(group.Name,"_",segment.Name!); //DrawGroup_Segment
                sb.EndLine("()");
                sb.OpenBrace();

                foreach (var member in segment.Members.AsSpan())
                    sb.AppendLine(member.Input!.Name, ".Draw();");

                sb.CloseBrace();
            }
            sb.AppendLine();

        }

        // DrawGroups
        /*
        foreach (var g in model.Groups.AsSpan())
        {
            var memberSpan = g.Members;
            if (memberSpan.Length == 0) continue;

            sb.AppendLine().AppendLine("public void Draw", g.IsRoot ? "Root" : g.Name, "()");
            sb.OpenBrace();
            foreach (var m in memberSpan.AsSpan())
            {
                if (m.Input is null) continue;
                sb.AppendLine(m.Name, ".Draw();");
            }

            sb.CloseBrace();
        }
        */
        sb.CloseBrace(); // class
        return sb.ToString();
    }

    private static void EmitGrop(SourceBuilder sb, InspectorGroup group, EquatableArray<EmitSegment> segments)
    {
        foreach (var segment in segments.AsSpan())
        foreach (var member in segment.Members.AsSpan())
        {
            EmitInputField(sb, member, group);
        }

        sb.EndLine();
    }


    private static void EmitInputField(SourceBuilder sb, InspectorMember member, InspectorGroup group)
    {
        sb.BeginLine("private readonly ");

        var access = CreateAccessPath(member, group);
        switch (member.Input)
        {
            case NumberInput: EmitInput(sb, member, access); break;
            case ColorInput: EmitColor(sb, member, access); break;
            case ComboInput: EmitCombo(sb, member, access); break;
            default: throw new UnreachableException(nameof(member.Input));
        }
    }

    private static void EmitInput(SourceBuilder sb, InspectorMember member, AccessPath access)
    {
        var input = (NumberInput)member.Input!;
        var isFloat = input.IsFloat();

        var inputType = isFloat ? $"FloatInput<{input.NumberType}>" : $"IntInput<{input.NumberType}>";
        sb.Append(inputType, " ", input.Name, " = new(").EndLine();
        sb.PushIndent();

        sb.AppendLine(member.GetLabelLiteral(), ", ");
        sb.AppendLine(input.GetInputStyleLiteral(), ", ");

        // Getter
        sb.AppendLine("static () => Unsafe.BitCast", $"<{member.TypeName}, {input.NumberType}>({access.Value}), ");
        sb.AppendLine(MakeSetter(member, in access, $"Unsafe.BitCast<{input.NumberType}, {member.TypeName}>(v)"), ", ");

        //
        sb.BeginLine();
        if (isFloat)
        {
            sb.Append(input.Speed).Append(", ").Append(input.Min).Append(", ").Append(input.Max);
            if (!string.IsNullOrEmpty(input.Format)) sb.Append(", ").Append(Symbols.FormatLiteral(input.Format, true));
        }
        else
        {
            sb.Append(input.Speed).Append(", ").Append((int)input.Min).Append(", ").Append((int)input.Max);
        }

        sb.EndLine();

        sb.PopIndent();
        sb.AppendLine(");");
    }

    private static void EmitColor(SourceBuilder sb, InspectorMember member, AccessPath access)
    {
        var input = (ColorInput)member.Input!;
        string castTo = "", castFrom = "", typeName = member.TypeName;
        if (typeName.EndsWith("Vector3") || typeName.EndsWith("Vector4") || typeName.EndsWith("ColorRgba"))
        {
            castTo = $"({member.TypeName})";
            castFrom = "(Color4)";
        }

        sb.Append("ColorInput ", input.Name, " = new(").EndLine();
        sb.PushIndent();

        sb.AppendLine(member.GetLabelLiteral(), ", ");

        //getter & setter
        sb.AppendLine($"static () => {castFrom}{access.Value}, ");
        sb.AppendLine(MakeSetter(member, in access, $"{castTo}v"), ", ");

        sb.AppendLine(Symbols.FormatPrimitive(input.HasAlpha, false, false));
        sb.PopIndent();
        sb.AppendLine(");");
    }

    private static void EmitCombo(SourceBuilder sb, InspectorMember member, AccessPath access)
    {
        var input = (ComboInput)member.Input!;
        string castTo = "", castFrom = "";
        if (member.TypeName != "int")
        {
            castTo = $"({member.TypeName})";
            castFrom = "(int)";
        }

        sb.Append("ComboInput ", input.Name, " = ComboInput.Create(").EndLine();
        sb.PushIndent();

        sb.AppendLine(member.GetLabelLiteral(), ", ");
        sb.AppendLine(input.Values, ", ");
        sb.AppendLine(input.Names, ", ");

        //getter & setter
        sb.AppendLine($"static () => {castFrom}{access.Value}, ");
        sb.AppendLine(MakeSetter(member, in access, $"{castTo}v"), ", ");
        sb.AppendLine(input.StartAt.ToString());
        if (!string.IsNullOrEmpty(input.Placeholder)) sb.AppendLine(", ", input.Placeholder);

        sb.PopIndent();
        sb.AppendLine(");");
    }

    private static string MakeSetter(InspectorMember member, in AccessPath access, string assignedValue)
    {
        return access.UsesStructCopy
            ? $"static v => {access.Owner} = {access.Owner} with {{ {member.Name} = {assignedValue} }}"
            : $"static v => {access.Value} = {assignedValue}";
    }

    private static AccessPath CreateAccessPath(InspectorMember member, InspectorGroup group)
    {
        if (group.IsRoot)
        {
            var ownerValue = $"Target.{member.Name}";
            return new AccessPath(ownerValue, ownerValue, false);
        }

        var owner = $"Target.{group.AccessPath}";
        var value = $"{owner}.{member.Name}";
        return new AccessPath(owner, value, group.Info.IsStructProperty());
    }

    private static EquatableArray<EmitSegment> BuildSegments(InspectorGroup group)
    {
        var dict = new Dictionary<string, List<InspectorMember>>(StringComparer.Ordinal);

        foreach (var member in group.Members.AsSpan())
        {
            var key = member.Segment ?? "";

            if (!dict.TryGetValue(key, out var list)) dict[key] = list = new List<InspectorMember>();
            list.Add(member);
        }

        var segments = new List<EmitSegment>(dict.Count);
        if (dict.Remove("", out var defaultMembers))
            segments.Add(new EmitSegment(null, defaultMembers.ToEquatableArray()));

        foreach (var pair in dict)
            segments.Add(new EmitSegment(pair.Key, pair.Value.ToEquatableArray()));

        return segments.ToEquatableArray();
    }
}