using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Generator.InspectorGen;

[Generator]
public sealed partial class InspectorGenerator : IIncrementalGenerator
{
    private const string MainAttributeFullName = "ConcreteEngine.Editor.Lib.EditorInspectorAttribute";
    private const string MainAttribute = "EditorInspectorAttribute";

    private const string InspectAttrib = "InspectAttribute";
    private const string IncludeAttrib = "InspectIncludeAttribute";
    private const string InputNumberAttrib = "InputNumberAttribute";
    private const string InputColorAttrib = "InputColorAttribute";
    private const string InputComboAttrib = "InputComboAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var valueProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(MainAttributeFullName, Predicates.IsObjectOrStruct, Build)
            .Where(static x => x != null!);

        context.RegisterSourceOutput(valueProvider, static (ctx, value) =>
        {
            var source = Emit(value);
            ctx.AddSource($"{value.TargetName}Inspector.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }


    private static InspectModel Build(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        var inspectorSym = (INamedTypeSymbol)ctx.TargetSymbol;
        var inspectorAttr = inspectorSym.GetAttributes().First(x => x.AttributeClass?.Name == MainAttribute);

        var targetSym =
            (INamedTypeSymbol)inspectorAttr.ConstructorArguments.First(x => x.Kind == TypedConstantKind.Type).Value!;
        var targetAttr = targetSym.GetAttributes().First(x => x.AttributeClass?.Name == InspectAttrib);
        //

        string? displayName = null;
        foreach (var (key, constant) in targetAttr.NamedArguments)
        {
            switch (key, constant.Value)
            {
                case ("DisplayName", string s): displayName = s; break;
            }
        }

        var members = GenerateMemberFor(targetSym);
        return new InspectModel(
            InspectorName: inspectorSym.Name,
            InspectorNs: inspectorSym.ContainingNamespace.ToDisplayString(),
            TargetName: targetSym.Name,
            TargetNs: targetSym.ContainingNamespace.ToDisplayString(),
            Members: members
        ) { DisplayName = displayName };
    }

    private static EquatableArray<TargetMemberInfo> GenerateMemberFor(INamedTypeSymbol targetSym)
    {
        List<TargetMemberInfo> list = new(4);

        var members = targetSym.GetMembers().Where(MemberFilter);
        foreach (var member in members)
        {
            if (CreateMember(member, null, null) is { } created)
            {
                list.Add(created);
                continue;
            }

            var includeAttr = member.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name is IncludeAttrib);
            if (includeAttr is not null)
            {
                var includeSym = member.GetFieldOrPropertyType();
                var includeAttrCtor = includeAttr.ConstructorArguments;

                var nestedAccessPath = member.Name;
                if (!includeAttrCtor.IsEmpty && includeAttrCtor[0].Value is string accessSuffix)
                    nestedAccessPath += $".{accessSuffix}";

                foreach (var nestedMember in includeSym.GetMembers().Where(MemberFilter))
                {
                    if (CreateMember(nestedMember, includeSym.Name, nestedAccessPath) is { } createdInner)
                        list.Add(createdInner);
                }
            }
        }

        return list.ToEquatableArray();

        static bool MemberFilter(ISymbol sym) =>
            sym is IPropertySymbol or IFieldSymbol && !sym.IsImplicitlyDeclared && !sym.GetAttributes().IsEmpty;

        static TargetMemberInfo? CreateMember(ISymbol sym, string? segment, string? nestedAccessPath)
        {
            var inputAttr = sym.GetAttributes().FirstOrDefault(static x =>
                x.AttributeClass?.Name is InputNumberAttrib or InputColorAttrib or InputComboAttrib);

            if (inputAttr == null) return null;

            var type = sym.GetFieldOrPropertyType();
            var inputField = MakeField(sym.Name, inputAttr, type);
            var ns = sym.ContainingNamespace.ToDisplayString();

            return new TargetMemberInfo(sym.Name, ns, type.ToDisplayString(), inputField)
            {
                NestedMemberName = nestedAccessPath, Segment = segment
            };
        }
    }


    private static string Emit(InspectModel model)
    {
        var sb = new SourceBuilder();
        sb.AutoGeneratedHeader(nameof(InspectorGenerator));
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ConcreteEngine.Core.Common.Numerics;");
        sb.AppendLine("using ConcreteEngine.Core.Engine.Editor;");
        sb.AppendLine("using ConcreteEngine.Editor.Lib.Inspection;");
        sb.AppendLine("using ConcreteEngine.Editor.Lib.Widgets;").AppendLine();

        sb.AppendLine($"namespace {model.InspectorNs};").AppendLine();

        sb.AppendLine($"internal static partial class {model.InspectorName}");
        sb.OpenBrace();

        // Members
        foreach (var m in model.Members)
        {
            if (m.Field is null) continue;
            EmitInput(m, sb);
            sb.AppendLine();
        }

        // Draw
        sb.AppendLine().AppendLine($"public static unsafe void Draw()");
        sb.OpenBrace();
        foreach (var m in model.Members)
        {
            if (m.Field is null) continue;
            sb.AppendLine(m.Name, ".Draw();");
        }

        sb.CloseBrace(); // Draw

        sb.CloseBrace(); // class
        return sb.ToString();
    }

    private static void EmitInput(TargetMemberInfo member, SourceBuilder sb)
    {
        var field = member.Field!;

        var label = Symbols.FormatLiteral(field.Label, true);
        var targetPath = member.NestedMemberName is null
            ? $"Target.{member.Name}"
            : $"Target.{member.NestedMemberName}.{member.Name}";

        sb.NewLine("private static readonly ");
        if (field is ColorField colorField)
        {
            sb.Append("ColorInput ", field.Name, " = new(").EndLine();
            sb.PushIndent();
            sb.AppendLine(label, ", ");
            sb.AppendLine($"static () => {targetPath}, ");
            sb.AppendLine($"static v => {targetPath} = v, ");
            sb.AppendLine(Symbols.FormatPrimitive(colorField.HasAlpha, false, false));
            sb.PopIndent();
            sb.AppendLine(");");
            return;
        }

        if (field is not InputField input) return;
        //var comp = (int)char.GetNumericValue(field.ValueType[^1]);
        var inputStyle = $"{nameof(InputStyle)}.{input.InputStyle.ToString()}";

        sb.Append(input.IsFloat ? "FloatInput" : "IntInput", $"<{input.ValueType}> ", input.Name, " = new(");
        sb.EndLine();
        
        sb.PushIndent();
        sb.AppendLine(label, ", ").AppendLine(inputStyle, ", ");
        sb.AppendLine($"static () => Unsafe.BitCast<{member.TypeName}, {input.ValueType}>({targetPath}), ");
        sb.AppendLine($"static v => {targetPath} = Unsafe.BitCast<{input.ValueType}, {member.TypeName}>(v), ");
        
        sb.NewLine();
        if (input.IsFloat)
        {
            sb.Append(input.Speed).Append(", ").Append(input.Min).Append(", ").Append(input.Max);
            if (input.Format is not null) sb.Append(", ").Append(input.Format);
        }
        else
        {
            sb.Append(input.Speed).Append(", ").Append((int)input.Min).Append(", ").Append((int)input.Max);
        }
        sb.EndLine();
        
        sb.PopIndent();
        sb.AppendLine(");");
    }

}

/*
 private static EquatableArray<TargetModel> Transformer(Compilation compilation, CancellationToken ct)
      {
          ct.ThrowIfCancellationRequested();
          var coreAssembly = compilation.SourceModule
              .ReferencedAssemblySymbols.FirstOrDefault(a => a.Name.EndsWith("Core.Engine"));

          if (coreAssembly is null) return [];

          var list = new List<TargetModel>();
          foreach (var type in GetAllTypes(coreAssembly.GlobalNamespace))
          {
              if (!type.IsPublicClassOrStruct()) continue;
              var attr = type.GetAttributes().FirstOrDefault(static it => it.AttributeClass?.Name == InspectAttrib);
              if (attr is not null && Generate(type, attr) is { } targetModel)
                  list.Add(targetModel);
          }

          return list.ToImmutableArray().AsEquatableArray();
      }
*/