using System.Diagnostics;

namespace Generator.InspectorGen;

internal static class InspectorGeneratorEmitter
{
    private readonly record struct AccessPath(string Owner, string Value, bool UsesStructCopy);

    private static void GenerateHeaders(SourceBuilder sb, string ns)
    {
        sb.AutoGeneratedHeader(nameof(InspectorGenerator));
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ConcreteEngine.Core.Common.Numerics;");
        sb.AppendLine("using ConcreteEngine.Core.Engine.Editor;");
        sb.AppendLine("using ConcreteEngine.Editor.Lib.Field;\n");

        sb.AppendLine("namespace ", ns, ";\n");
    }


    public static string Emit(InspectModel model)
    {
        var sb = new SourceBuilder(4096 * 2);
        GenerateHeaders(sb, model.InspectorNs);

        sb.AppendLine("internal sealed partial class ", model.InspectorName);
        sb.OpenBrace();

        // Groups
        foreach (var g in model.Groups.AsSpan())
        foreach (var m in g.Members.AsSpan())
        {
            if (m.Input is null) continue;
            EmitInputField(sb, m, g);
            sb.AppendLine();
        }

        // DrawGroups
        foreach (var g in model.Groups.AsSpan())
        {
            var memberSpan = g.Members;
            if (memberSpan.Length == 0) continue;

            sb.AppendLine().AppendLine("public void Draw", g.IsRoot ? "Root" : g.Name, "()");
            sb.OpenBrace();
            foreach (var m in memberSpan.AsSpan())
            {
                if (m.Input is null) continue;
                sb.AppendLine(m.Name, ".Draw();");
            }

            sb.CloseBrace();
        }

        sb.CloseBrace(); // class
        return sb.ToString();
    }

    private static void EmitInputField(SourceBuilder sb, InspectorMember member, InspectorGroup group)
    {
        sb.NewLine("private readonly ");

        var access = CreateAccessPath(member, group);
        switch (member.Input)
        {
            case NumberInput: EmitInput(sb, member, access); break;
            case ColorInput: EmitColor(sb, member, access); break;
            case ComboInput: EmitCombo(sb, member, access); break;
            default: throw new UnreachableException(nameof(member.Input));
        }
    }

    private static void EmitInput(SourceBuilder sb, InspectorMember member, AccessPath access)
    {
        var input = (NumberInput)member.Input!;
        var isFloat = input.IsFloat();

        var inputType = isFloat ? $"FloatInput<{input.NumberType}>" : $"IntInput<{input.NumberType}>";
        sb.Append(inputType, " ", input.Name, " = new(").EndLine();
        sb.PushIndent();

        sb.AppendLine(member.GetDisplayNameString(), ", ");
        sb.AppendLine(input.GetInputStyleText(), ", ");

        // Getter
        sb.AppendLine("static () => Unsafe.BitCast", $"<{member.TypeName}, {input.NumberType}>({access.Value}), ");
        sb.AppendLine(MakeSetter(member, in access, $"Unsafe.BitCast<{input.NumberType}, {member.TypeName}>(v)"), ", ");

        //
        sb.NewLine();
        if (isFloat)
        {
            sb.Append(input.Speed).Append(", ").Append(input.Min).Append(", ").Append(input.Max);
            if (!string.IsNullOrEmpty(input.Format)) sb.Append(", ").Append(Symbols.FormatLiteral(input.Format, true));
        }
        else
        {
            sb.Append(input.Speed).Append(", ").Append((int)input.Min).Append(", ").Append((int)input.Max);
        }

        sb.EndLine();

        sb.PopIndent();
        sb.AppendLine(");");
    }

    private static void EmitColor(SourceBuilder sb, InspectorMember member, AccessPath access)
    {
        var input = (ColorInput)member.Input!;
        string castTo = "", castFrom = "", typeName = member.TypeName;
        if (typeName.EndsWith("Vector3") || typeName.EndsWith("Vector4") || typeName.EndsWith("ColorRgba"))
        {
            castTo = $"({member.TypeName})";
            castFrom = "(Color4)";
        }

        sb.Append("ColorInput ", input.Name, " = new(").EndLine();
        sb.PushIndent();

        sb.AppendLine(member.GetDisplayNameString(), ", ");

        //getter & setter
        sb.AppendLine($"static () => {castFrom}{access.Value}, ");
        sb.AppendLine(MakeSetter(member, in access, $"{castTo}v"), ", ");

        sb.AppendLine(Symbols.FormatPrimitive(input.HasAlpha, false, false));
        sb.PopIndent();
        sb.AppendLine(");");
    }

    private static void EmitCombo(SourceBuilder sb, InspectorMember member, AccessPath access)
    {
        var input = (ComboInput)member.Input!;
        string castTo = "", castFrom = "";
        if (member.TypeName != "int")
        {
            castTo = $"({member.TypeName})";
            castFrom = "(int)";
        }

        sb.Append("ComboInput ", input.Name, " = ComboInput.Create(").EndLine();
        sb.PushIndent();

        sb.AppendLine(member.GetDisplayNameString(), ", ");
        sb.AppendLine(input.Values, ", ");
        sb.AppendLine(input.Names, ", ");

        //getter & setter
        sb.AppendLine($"static () => {castFrom}{access.Value}, ");
        sb.AppendLine(MakeSetter(member, in access, $"{castTo}v"), ", ");
        sb.AppendLine(input.StartAt.ToString());
        if(!string.IsNullOrEmpty(input.Placeholder)) sb.AppendLine(", ", input.Placeholder);

        sb.PopIndent();
        sb.AppendLine(");");
    }
    
    private static string MakeSetter(InspectorMember member, in AccessPath access, string assignedValue)
    {
        return access.UsesStructCopy
            ? $"static v => {access.Owner} = {access.Owner} with {{ {member.Name} = {assignedValue} }}"
            : $"static v => {access.Value} = {assignedValue}";
    }

    private static AccessPath CreateAccessPath(InspectorMember member, InspectorGroup group)
    {
        if (group.IsRoot)
        {
            var ownerValue = $"Target.{member.Name}";
            return new AccessPath(ownerValue, ownerValue, false);
        }

        var owner = $"Target.{group.AccessPath}";
        var value = $"{owner}.{member.Name}";
        return new AccessPath(owner, value, group.Info.IsStructProperty());
    }
}