using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Generator.InspectorGen.InspectorGeneratorData;

namespace Generator.InspectorGen;

[Generator]
public sealed partial class InspectorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var memberModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(AttribInspect, IsPropOrVarMember, BuildMemberModel)
            .Where(static m => m is not null).Select(static (m, _) => m!);

        var grouped = memberModels.Collect();
        context.RegisterSourceOutput(grouped, static (ctx, members) =>
        {
            foreach (var typeGroup in members.GroupBy(m => m.TypeName))
            {
                var it = typeGroup.First();
                var source = Emit(it, typeGroup.ToImmutableArray());
                ctx.AddSource(MakeInspectorFileName(it.TypeName), SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static InspectModel? BuildMemberModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        var memberSym = ctx.TargetSymbol;
        var containingType = memberSym.ContainingType;
        if (containingType is null || ctx.Attributes.Length < 2) return null;

        AttributeData? inspectAttr = null, fieldAttr = null;
        foreach (var it in ctx.Attributes)
        {
            if (it.AttributeClass is null) continue;
            if (it.AttributeClass.Name == "InspectAttribute") inspectAttr = it;
            else if (it.AttributeClass.Name.EndsWith("FieldAttribute", StringComparison.Ordinal)) fieldAttr = it;
        }

        if (inspectAttr == null || fieldAttr == null) return null;

        var inspectAttrCtor = inspectAttr.ConstructorArguments;
        if (inspectAttrCtor.IsEmpty || inspectAttrCtor[0].Value is not string displayName)
            displayName = memberSym.Name; // nameof({containingType.Name}.{memberSym.Name})

        var field = MakeField(ctx.Attributes[1], containingType);
        if (field == null) return null;

        return new InspectModel
        {
            TypeName = containingType.Name,
            MemberName = memberSym.Name,
            MemberTypeName = memberSym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            DisplayName = displayName,
            Field = field
        };

    }
    

    private static string Emit(InspectModel it, ImmutableArray<InspectModel> members)
    {
        var target = $"{it.TypeName}Target";

        var sb = new SourceBuilder();
        sb.AutoGeneratedHeader(nameof(InspectorGenerator));
        sb.AppendLine($"namespace {InspectorNs};").AppendLine();

        sb.AppendLine($"internal static partial class InspectorBindings");
        sb.OpenBrace();

        sb.AppendLine($"private static {it.TypeName}? {target} => global::Inspector<{it.TypeName}>.Target;");
        sb.AppendLine();

        sb.AppendLine($"public static void Register{it.TypeName}()");
        sb.OpenBrace();

        foreach (var m in members)
        {
            sb.AppendLine($"global::Inspector<{it.TypeName}>.Register<{m.Field.ValueType}>(");
            sb.PushIndent();
            sb.AppendLine($"{m.MemberName},");
            EmitInput(m, sb);
            sb.AppendLine($"static () => ({m.Field.ValueType}){target}!.{m.MemberName},");
            sb.AppendLine($"static v  => {target}!.{m.MemberName} = ({m.MemberTypeName})v");
            sb.PopIndent();
            sb.AppendLine(");");
            
        }

        sb.CloseBrace(); // Register()

        sb.CloseBrace(); // class

        return sb.ToString();
    }

    private static void EmitInput(InspectModel member, SourceBuilder sb)
    {
        var field = member.Field;

        if (field is ColorField colorField)
        {
            sb.AppendLine($"new ColorInput({member.DisplayName}, {colorField.HasAlpha.ToString()}),");
            return;
        }

        if (field is ComboField comboField)
        {
            sb.AppendLine($"ComboInput.MakeFromEnumCache<{member.MemberTypeName}>({member.DisplayName}),");
            return;
        }

        if (field is not InputField input) return;
        
        if (field.ValueType.StartsWith("Int", StringComparison.Ordinal))
        {
            sb.AppendIndent();
            sb.Append($"new IntInput<{input.ValueType}>(");
            sb.Append(member.DisplayName).Append(", ").Append((int)input.Kind).Append(", ");
            sb.Append(input.Speed).Append(", ").Append((int)input.Min).Append(", ").Append((int)input.Max);
            sb.Append("),\n");
            return;
        }
        
        sb.AppendIndent();
        sb.Append($"new FloatInput<{input.ValueType}>(");
        sb.Append(member.DisplayName).Append(", ").Append((int)input.Kind).Append(", ");
        sb.Append(input.Speed).Append(", ").Append(input.Min).Append(", ").Append(input.Max);
        if(input.Format is not null) sb.Append(", ").Append(input.Format);
        sb.Append("),\n");


    }
}