using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Generator.EnumCachedGen;

[Generator]
public sealed class EnumCachedGenerator : IIncrementalGenerator
{
    private const string ResultNamespace = "ConcreteEngine.Generated";
    private const string RegisterFuncName = "ConcreteEngine.Core.Common.StaticEnumCache.Register";
    private const string ResultFileName = "StaticEnumCache.Setup.g.cs";
    private const string AttributeName = "EnumCachedAttribute";
    private const string AttributeFullName = $"ConcreteEngine.Core.Common.{AttributeName}";

    private sealed record EnumItem(
        string TypeName,
        string Namespace,
        EquatableArray<string> Names,
        EquatableArray<int> Values);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        
       var enums = context.SyntaxProvider
           .ForAttributeWithMetadataName(AttributeFullName, Predicates.IsEnumWithAttrib, Build)
           .Where(static x => x is not null).Collect();

       /*
       var filteredItems = enums
           .Combine(enabled)
           .Where(static tuple => tuple.Right)
           .Select(static (tuple, _) => tuple.Left)
           .Collect();*/
       
        context.RegisterSourceOutput(enums, static (ctx, it) =>
        {
            var source = Emit(it);
            ctx.AddSource(ResultFileName, SourceText.From(source, Encoding.UTF8));
        });
    }


    private static EnumItem? Build(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        
        var enumSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var members = enumSymbol.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue);

        var names = members.Select(m => Symbols.FormatLiteral(m.Name, true)).ToEquatableArray();
        var values = members.Select(m => int.Parse(m.ConstantValue!.ToString()!)).ToEquatableArray();
        var ns = enumSymbol.ContainingNamespace.ToDisplayString();

        return new EnumItem(enumSymbol.Name, ns, names, values);
    }

    private static string Emit(ImmutableArray<EnumItem?> enums)
    {
        var sb = new SourceBuilder();
        sb.AutoGeneratedHeader(nameof(EnumCachedGenerator));
        
        sb.AppendLine($"namespace {ResultNamespace};").AppendLine();

        sb.AppendLine($"internal static class StaticEnumCacheSetup");
        sb.OpenBrace();
        sb.AppendLine("[System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine($"internal static void Setup()");
        sb.OpenBrace();
        foreach (var it in enums)
        {
            if (it is null) continue;
            var names = string.Join(",", it.Names.GetMainArray());
            sb.AppendLine($"{RegisterFuncName}(typeof({it.Namespace}.{it.TypeName}), [{names}]);");
        }

        sb.CloseBrace();
        sb.CloseBrace();
        return sb.ToString();
    }
}