using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Generator.EnumCachedGen;

[Generator]
public sealed class EnumExtGenerator : IIncrementalGenerator
{
    private const string AttributeName = "EnumExtAttribute";
    private const string AttributeFullName = $"ConcreteEngine.Core.Common.{AttributeName}";

    private sealed record EnumItem(
        bool IsInternal,
        Accessibility Accessibility,
        string TypeName,
        string Namespace,
        EquatableArray<string> Names,
        EquatableArray<int> Values);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enums = context.SyntaxProvider
            .ForAttributeWithMetadataName(AttributeFullName, Predicates.IsEnumWithAttrib, Build)
            .Where(static x => x is not null);

        context.RegisterSourceOutput(enums, static (ctx, it) =>
        {
            var source = Emit(it);
            ctx.AddSource($"EnumExtended.{it.TypeName}", SourceText.From(source, Encoding.UTF8));
        });
    }


    private static EnumItem? Build(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        var enumSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var isInternal = enumSymbol.ContainingSymbol.DeclaredAccessibility == Accessibility.Internal;
        var members = enumSymbol.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue);

        var names = members.Select(m => m.Name).ToEquatableArray();
        var values = members.Select(m => int.Parse(m.ConstantValue!.ToString()!)).ToEquatableArray();
        var ns = enumSymbol.ContainingNamespace.ToDisplayString();

        return new EnumItem(isInternal,enumSymbol.ContainingSymbol.DeclaredAccessibility, enumSymbol.Name, ns, names, values);
    }

    private static string Emit(EnumItem it)
    {
        //var names = string.Join(",", it.Names.GetMainArray());
        //var values = string.Join(",", it.Values.GetMainArray());

        var sb = new SourceBuilder();
        sb.AutoGeneratedHeader(nameof(EnumCachedGenerator));

        sb.AppendLine($"namespace {it.Namespace};").AppendLine();
        sb.AppendLine($"//{it.Accessibility}");
        var access = it.IsInternal ? "internal" : "public";
        sb.AppendLine($"{access} static partial class EnumExtended");
        sb.OpenBrace();
        
        sb.AppendLine($"public static string ToStringFast(this {it.TypeName} value) => value switch");
        sb.OpenBrace();
        
        foreach (var name in it.Names)
        {
            var fullName = $"{it.TypeName}.{name}";
            sb.AppendIndent().Append(fullName).Append(" => nameof(").Append(fullName).Append("),\n");
        }
        
        sb.CloseBrace(";");
        
        sb.CloseBrace();

        return sb.ToString();
    }
}