using System.Text;
using Generator.Misc;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Generator.EnumExtGen;

[Generator]
public sealed class EnumExtGenerator : IIncrementalGenerator
{
    private const string AttributeName = "EnumExtAttribute";
    private const string AttributeFullName = "ConcreteEngine.Core.Common.Attributes." + AttributeName;

    private const int AggressiveInliningLimit = 12;

    private record struct EnumExtAttrib(bool ToUtf8, bool ToIndex);

    private sealed record BuildResult(
        EquatableArray<(string Name, object Value)> Data,
        string TypeName,
        string Namespace,
        string Primitive,
        bool IsInternal,
        EnumExtAttrib Attrib
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enums = context.SyntaxProvider
            .ForAttributeWithMetadataName(AttributeFullName, Predicates.IsEnumNode, Build)
            .Where(static x => x != null!);

        context.RegisterSourceOutput(enums, static (ctx, it) =>
        {
            var source = Generate(it!);
            ctx.AddSource($"EnumExtended.{it!.TypeName}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }


    private static BuildResult? Build(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        var enumSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        var param = new EnumExtAttrib();
        var attr = enumSymbol.GetAttributes().First(x => x.AttributeClass?.Name == AttributeName);
        foreach (var it in attr.NamedArguments)
        {
            if (it.Value.Kind != TypedConstantKind.Primitive) continue;
            var boxedValue = it.Value.Value;
            if (boxedValue is bool bvalue)
            {
                switch (it.Key)
                {
                    case "ToIndex": param.ToIndex = bvalue; break;
                    case "ToUtf8": param.ToUtf8 = bvalue; break;
                }
            }
/*
            if (boxedValue is char cvalue)
            {
                switch (it.Key)
                {
                    case "Suffix": param.Suffix = cvalue; break;
                    case "Prefix": param.Prefix = cvalue; break;
                }
            }
*/
        }

        var data = enumSymbol.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue)
            .Select(static m => (m.Name, ConstantValue: m.ConstantValue!)).ToEquatableArray();

        if (data.AsSpan().Length == 0) return null;

        return new BuildResult(
            Data: data,
            Attrib: param,
            IsInternal: enumSymbol.DeclaredAccessibility == Accessibility.Internal,
            Primitive: ConstantValueToPrimitive(data[0].ConstantValue),
            TypeName: enumSymbol.Name,
            Namespace: enumSymbol.ContainingNamespace.ToDisplayString());
    }

    private static string Generate(BuildResult it)
    {
        var count = it.Data.Length;
        var nameLiterals = it.Data.Array.Select(x => $"\"{x.Name}\"").ToArray();
        var sb = new SourceBuilder(4096);

        sb.AutoGeneratedHeader(nameof(EnumExtGenerator), it.Namespace);

        sb.AppendLine(it.IsInternal ? "internal" : "public", " static class ", it.TypeName, "Ext");
        sb.OpenBrace();

        //
        sb.BeginLine();
        sb.Builder.Append($"public static readonly int Count = {count};");
        sb.EndLine("\n");

        sb.BeginLine();
        sb.Builder.Append($"private static readonly {it.Primitive}[] values = [");
        sb.Builder.AppendJoin(',', it.Data.Array.Select(static x => x.Value));
        sb.EndLine("];");

        sb.BeginLine("private static readonly string[] names = [");
        sb.Builder.AppendJoin(',', nameLiterals);
        sb.EndLine("];");

        //
        sb.AppendLine().BeginLine();
        sb.Builder.AppendLine($"public static ReadOnlySpan<{it.Primitive}> Values => values;");
        sb.AppendLine("public static ReadOnlySpan<string> Names => names;\n");

        //
        if (it.Attrib.ToIndex)
        {
            sb.AppendLine().AppendLine(Consts.AggressiveInliningText);
            sb.BeginLine();
            sb.Builder.Append($"public static int ToIndex(this {it.TypeName} value) => (int)value - 1;");
            sb.EndLine();
        }

        //
        if (count <= AggressiveInliningLimit)
            sb.AppendLine().AppendLine(Consts.AggressiveInliningText);

        sb.BeginLine();
        sb.Builder.Append($"public static string ToText(this {it.TypeName} value) => value switch");
        sb.EndLine();

        sb.OpenBrace();

        for (int i = 0; i < it.Data.Length; i++)
        {
            sb.BeginLine(it.TypeName);
            sb.Builder.AppendLine($".{it.Data[i].Name} => {nameLiterals[i]},");
        }

        sb.AppendLine("_ => throw new ArgumentOutOfRangeException(nameof(value))");

        sb.CloseBrace(";");
        //

        if (it.Attrib.ToUtf8)
        {
            if (count <= AggressiveInliningLimit)
                sb.AppendLine().AppendLine(Consts.AggressiveInliningText);

            sb.BeginLine();
            sb.Builder.Append($"public static ReadOnlySpan<byte> ToUtf8(this {it.TypeName} value) => value switch");
            sb.EndLine();

            sb.OpenBrace();

            for (var i = 0; i < it.Data.Length; i++)
            {
                sb.BeginLine(it.TypeName);
                sb.Builder.AppendLine($".{it.Data[i].Name} => {nameLiterals[i]}u8,");

            }
            sb.AppendLine("_ => throw new ArgumentOutOfRangeException(nameof(value))");

            sb.CloseBrace(";");
        }

        sb.CloseBrace();

        return sb.ToString();
    }

    private static string ConstantValueToPrimitive(object constantValue) =>
        constantValue switch
        {
            byte => "byte",
            sbyte => "sbyte",
            short => "short",
            ushort => "ushort",
            int => "int",
            uint => "uint",
            long => "long",
            ulong => "ulong",
            _ => throw new ArgumentOutOfRangeException()
        };
}