using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Generator.EnumExtGen;

[Generator]
public sealed class EnumExtGenerator : IIncrementalGenerator
{
    private const string AttributeName = "EnumExtAttribute";
    private const string AttributeFullName = "ConcreteEngine.Core.Common.Attributes." + AttributeName;

    private sealed record EnumItem(
        EquatableArray<(string Name, object Value)> Data,
        string TypeName,
        string Namespace,
        string Primitive,
        bool IsIndex,
        bool IsUtf8,
        bool IsInternal
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enums = context.SyntaxProvider
            .ForAttributeWithMetadataName(AttributeFullName, Predicates.IsEnumWithAttrib, Build)
            .Where(static x => x is not null);

        context.RegisterSourceOutput(enums, static (ctx, it) =>
        {
            var source = Emit(it!);
            ctx.AddSource($"EnumExtended.{it!.TypeName}", SourceText.From(source, Encoding.UTF8));
        });
    }


    private static EnumItem Build(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        var enumSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        bool isIndex = false, isUtf8 = false;
        var attr = enumSymbol.GetAttributes().First(x => x.AttributeClass?.Name == AttributeName);
        foreach (var it in attr.NamedArguments)
        {
            if (it.Value.Kind != TypedConstantKind.Primitive || it.Value.Value is not bool value) continue;
            switch (it.Key)
            {
                case "Index": isIndex = value; break;
                case "Utf8": isUtf8 = value; break;
            }
        }

        var data = enumSymbol.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue)
            .Select(static m => (m.Name, ConstantValue: m.ConstantValue!)).ToEquatableArray();
        
        string primitive = data[0].ConstantValue switch
        {
            byte => "byte",
            sbyte => "sbyte",
            short => "short",
            ushort => "ushort",
            int  => "int",
            uint  => "uint",
            long  => "long",
            ulong => "ulong",
            _ => throw new ArgumentOutOfRangeException()
        };
        return new EnumItem(
            Data: data,
            Primitive:primitive,
            IsIndex: isIndex,
            IsUtf8: isUtf8,
            IsInternal: enumSymbol.DeclaredAccessibility == Accessibility.Internal,
            TypeName: enumSymbol.Name,
            Namespace: enumSymbol.ContainingNamespace.ToDisplayString());
    }

    private static string Emit(EnumItem it)
    {
        var sb = new SourceBuilder(4096);
        sb.AutoGeneratedHeader(nameof(EnumExtGenerator));

        sb.AppendLine($"namespace {it.Namespace};").AppendLine();

        var access = it.IsInternal ? "internal" : "public";

        sb.AppendLine($"{access} static class {it.TypeName}Ext");
        sb.OpenBrace();

        //
        sb.AppendLine($"public static readonly int Count = {it.Data.Length};").AppendLine();

        sb.AppendIndent($"private static readonly {it.Primitive}[] values = [");
        sb.Builder.AppendJoin(',', it.Data.GetMainArray().Select(static x => x.Value));
        sb.Append("];\n");

        sb.AppendIndent("private static readonly string[] names = [");
        sb.Builder.AppendJoin(',', it.Data.GetMainArray().Select(x => Symbols.FormatLiteral(x.Name, true)));
        sb.Append("];\n");
        
        //
        sb.AppendLine();
        sb.AppendLine($"public static ReadOnlySpan<{it.Primitive}> Values => values;");
        sb.AppendLine("public static ReadOnlySpan<string> Names => names;").AppendLine();
        
        //
        if (it.IsIndex)
        {
            sb.AppendLine().AppendLine(Consts.AggressiveInliningText);
            sb.AppendLine($"public static int ToIndex(this {it.TypeName} value) => (int)value - 1;");
        }

        //
        sb.AppendLine().AppendLine(Consts.AggressiveInliningText);
        sb.AppendLine($"public static string ToText(this {it.TypeName} value) => value switch");
        sb.OpenBrace();

        foreach (var data in it.Data)
        {
            var fullName = $"{it.TypeName}.{data.Name}";
            sb.AppendIndent().Append(fullName).Append(" => nameof(").Append(fullName).Append("),\n");
        }

        sb.CloseBrace(";");
        //

        if (it.IsUtf8)
        {
            sb.AppendLine().AppendLine(Consts.AggressiveInliningText);
            sb.AppendLine($"public static ReadOnlySpan<byte> ToUtf8(this {it.TypeName} value) => value switch");
            sb.OpenBrace();

            foreach (var data in it.Data)
            {
                var fullName = $"{it.TypeName}.{data.Name}";
                var nameTxt = Symbols.FormatLiteral(data.Name, true);
                sb.AppendIndent().Append(fullName).Append(" => ").Append(nameTxt).Append("u8,\n");
            }

            sb.CloseBrace(";");

        }


        sb.CloseBrace();

        return sb.ToString();
    }
}