using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace Generator;

internal ref struct SourceBuilder
{
    private const string IndentUnit = "    ";

    private readonly StringBuilder _sb;

    private int _indent;

    public SourceBuilder(int capacity)
    {
        _indent = 0;
        _sb = new StringBuilder(capacity);
    }
    public SourceBuilder() : this(4096) {}

    public readonly StringBuilder Builder => _sb;

    public void PushIndent() => _indent++;
    public void PopIndent() => _indent--;

    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendLine(string line = "")
    {
        if (line.Length > 0)
            IndentLine(line);
        
        _sb.AppendLine();
        return ref this;
    }
    
    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendLine(string s1, string s2, string? s3 = null, string? s4 = null)
    {
        for (var i = 0; i < _indent; i++) _sb.Append(IndentUnit);
        _sb.Append(s1).Append(s2);
        if (s3 != null) _sb.Append(s3);
        if (s4 != null) _sb.Append(s4);
        return ref this;
    }

    
    [UnscopedRef]
    public readonly ref readonly SourceBuilder IndentLine(string line = "")
    {
        for (var i = 0; i < _indent; i++) _sb.Append(IndentUnit);
        _sb.Append(line);
        return ref this;
    }
    
    [UnscopedRef]
    public readonly ref readonly SourceBuilder EndLine(string line = "")
    {
        _sb.AppendLine(line);
        return ref this;
    }


    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(string text)
    {
        _sb.Append(text);
        return ref this;
    }

    
    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(int v)
    {
        _sb.Append(v);
        return ref this;
    }
    
    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(float v)
    {
        _sb.Append(v);
        return ref this;
    }

    [UnscopedRef]
    public ref readonly SourceBuilder OpenBrace()
    {
        AppendLine("{");
        _indent++;
        return ref this;
    }

    [UnscopedRef]
    public ref readonly SourceBuilder CloseBrace(string suffix = "")
    {
        _indent--;
        AppendLine("}" + suffix);
        return ref this;
    }

    [UnscopedRef]
    public readonly void AutoGeneratedHeader(string generatorName, string? namespaceName = null)
    {
        AppendLine("// <auto-generated/>");
        AppendLine($"// Generator: {generatorName}");
        AppendLine("// Do NOT edit – changes will be overwritten on next build.");
        AppendLine("#nullable enable");
        AppendLine();
        if (!string.IsNullOrEmpty(namespaceName))
            AppendLine($"namespace {namespaceName};").AppendLine();
    }

    public override readonly string ToString() => _sb.ToString();
}
