using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace Generator;

internal ref struct SourceBuilder
{
    private const string IndentUnit = "    ";

    private readonly StringBuilder _sb;

    private int _indent;

    public SourceBuilder(int capacity)
    {
        _indent = 0;
        _sb = new StringBuilder(capacity);
    }

    public SourceBuilder() : this(4096) { }

    public readonly StringBuilder Builder => _sb;

    public void PushIndent() => _indent++;
    public void PopIndent() => _indent--;

    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendLine(string line = "")
    {
        if (line.Length > 0) NewLine(line);
        _sb.AppendLine();
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendLine(params ReadOnlySpan<string> texts)
    {
        if (texts.Length > 1)
        {
            NewLine(texts[0]);
            Append(texts.Slice(1));
        }

        _sb.AppendLine();
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder NewLine(string line = "")
    {
        for (var i = 0; i < _indent; i++) _sb.Append(IndentUnit);
        _sb.Append(line);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder EndLine(string line = "")
    {
        _sb.AppendLine(line);
        return ref this;
    }
    
    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendIf(bool condition, params ReadOnlySpan<string> texts)
    {
        if (!condition) return ref this;
        foreach (var it in texts) _sb.Append(it);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(params ReadOnlySpan<string> texts)
    {
        foreach (var it in texts) _sb.Append(it);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendJoin(string s, params ReadOnlySpan<string> texts)
    {
        for (var i = 0; i < texts.Length; i++)
        {
            _sb.Append(texts[i]);
            if (i < texts.Length - 1) _sb.Append(s);
        }

        return ref this;
    }


    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(string text)
    {
        _sb.Append(text);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(int v)
    {
        _sb.Append(v);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(float v)
    {
        _sb.Append(v.ToFloatStr());
        return ref this;
    }

    [UnscopedRef]
    public ref readonly SourceBuilder OpenBrace()
    {
        AppendLine("{");
        _indent++;
        return ref this;
    }

    [UnscopedRef]
    public ref readonly SourceBuilder CloseBrace(string suffix = "")
    {
        _indent--;
        AppendLine("}" + suffix);
        return ref this;
    }

    [UnscopedRef]
    public readonly void AutoGeneratedHeader(string generatorName, string? namespaceName = null)
    {
        AppendLine("// <auto-generated/>");
        AppendLine($"// Generator: {generatorName}");
        AppendLine("// Do NOT edit – changes will be overwritten on next build.");
        AppendLine("#nullable enable");
        AppendLine();
        if (!string.IsNullOrEmpty(namespaceName))
            AppendLine($"namespace {namespaceName};").AppendLine();
    }

    public override readonly string ToString() => _sb.ToString();
}