using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Text;
using Generator.Misc;

namespace Generator;

public static class StringBuilderExtensions{
    public static StringBuilder AppendLiteral(this StringBuilder sb, string str)
    {
        sb.Append($"\"{str}\"");
        return sb;
    }
}

internal ref struct SourceBuilder
{
    private const string IndentUnit = "    ";

    private readonly StringBuilder _sb;

    private int _indent;

    public SourceBuilder(int capacity)
    {
        _indent = 0;
        _sb = new StringBuilder(capacity);
    }

    public SourceBuilder() : this(4096) { }

    public readonly StringBuilder Builder => _sb;

    public void PushIndent() => _indent++;
    public void PopIndent() => _indent--;

    [UnscopedRef]
    public readonly ref readonly SourceBuilder BeginLine(string line = "")
    {
        for (var i = 0; i < _indent; i++) _sb.Append(IndentUnit);
        _sb.Append(line);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder EndLine(string line = "")
    {
        _sb.AppendLine(line);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendLine(string line = "")
    {
        if (line.Length > 0) BeginLine(line);
        _sb.AppendLine();
        return ref this;
    }


    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendLine(params ReadOnlySpan<string> texts)
    {
        if (texts.Length > 1)
        {
            BeginLine(texts[0]);
            Append(texts.Slice(1));
        }

        _sb.AppendLine();
        return ref this;
    }


    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(params ReadOnlySpan<string> texts)
    {
        foreach (var it in texts) _sb.Append(it);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendJoin<T>(string s, params ReadOnlySpan<T> values)
    {
        for (var i = 0; i < values.Length; i++)
        {
            _sb.Append(values[i]);
            if (i < values.Length - 1) _sb.Append(s);
        }

        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendJoin<T>(string s, EquatableArray<T> array) where T : IEquatable<T>
    {
        return ref AppendJoin(s, array.AsSpan());
    }


    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(string text)
    {
        _sb.Append(text);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(int v)
    {
        _sb.Append(v);
        return ref this;
    }

    [UnscopedRef]
    public readonly ref readonly SourceBuilder Append(float v)
    {
        _sb.Append(v.ToString(CultureInfo.InvariantCulture)).Append('f');
        return ref this;
    }
    
    [UnscopedRef]
    public readonly ref readonly SourceBuilder AppendLiteral(string str)
    {
        _sb.Append($"\"{str}\"");
        return ref this;
    }

    [UnscopedRef]
    public ref readonly SourceBuilder OpenBrace()
    {
        AppendLine("{");
        _indent++;
        return ref this;
    }

    [UnscopedRef]
    public ref readonly SourceBuilder CloseBrace(string suffix = "")
    {
        _indent--;
        AppendLine("}" + suffix);
        return ref this;
    }
    
    

    [UnscopedRef]
    public readonly void AutoGeneratedHeader(string generatorName, string? namespaceName = null)
    {
        AppendLine("// <auto-generated/>");
        AppendLine($"// Generator: ", generatorName);
        AppendLine("// Do NOT edit – changes will be overwritten on next build.");
        AppendLine("#nullable enable").AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
            AppendLine($"namespace ", namespaceName, ";").AppendLine();
    }

    public override readonly string ToString() => _sb.ToString();
}